/*
 * generated by Xtext 2.30.0
 */
package de.htwdd.sf.beleg.s85769s88750;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
