/**
 * generated by Xtext 2.30.0
 */
package de.htwdd.sf.beleg.s85769s88750.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Infinitiv</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s85769s88750.myDsl.Infinitiv#getWord <em>Word</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.beleg.s85769s88750.myDsl.MyDslPackage#getInfinitiv()
 * @model
 * @generated
 */
public interface Infinitiv extends EObject
{
  /**
   * Returns the value of the '<em><b>Word</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Word</em>' attribute.
   * @see #setWord(String)
   * @see de.htwdd.sf.beleg.s85769s88750.myDsl.MyDslPackage#getInfinitiv_Word()
   * @model
   * @generated
   */
  String getWord();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s85769s88750.myDsl.Infinitiv#getWord <em>Word</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Word</em>' attribute.
   * @see #getWord()
   * @generated
   */
  void setWord(String value);

} // Infinitiv
