/**
 * generated by Xtext 2.30.0
 */
package de.htwdd.sf.beleg.s85769s88750.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Title</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s85769s88750.myDsl.Title#getSubstantiv <em>Substantiv</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s85769s88750.myDsl.Title#getVerb <em>Verb</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.beleg.s85769s88750.myDsl.MyDslPackage#getTitle()
 * @model
 * @generated
 */
public interface Title extends EObject
{
  /**
   * Returns the value of the '<em><b>Substantiv</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Substantiv</em>' attribute.
   * @see #setSubstantiv(String)
   * @see de.htwdd.sf.beleg.s85769s88750.myDsl.MyDslPackage#getTitle_Substantiv()
   * @model
   * @generated
   */
  String getSubstantiv();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s85769s88750.myDsl.Title#getSubstantiv <em>Substantiv</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Substantiv</em>' attribute.
   * @see #getSubstantiv()
   * @generated
   */
  void setSubstantiv(String value);

  /**
   * Returns the value of the '<em><b>Verb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Verb</em>' attribute.
   * @see #setVerb(String)
   * @see de.htwdd.sf.beleg.s85769s88750.myDsl.MyDslPackage#getTitle_Verb()
   * @model
   * @generated
   */
  String getVerb();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s85769s88750.myDsl.Title#getVerb <em>Verb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Verb</em>' attribute.
   * @see #getVerb()
   * @generated
   */
  void setVerb(String value);

} // Title
