/**
 * generated by Xtext 2.30.0
 */
package de.htwdd.sf.beleg.s85769s88750.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ziel Wunsch</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s85769s88750.myDsl.Ziel_Wunsch#getGoal <em>Goal</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s85769s88750.myDsl.Ziel_Wunsch#getInfinitiv <em>Infinitiv</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.beleg.s85769s88750.myDsl.MyDslPackage#getZiel_Wunsch()
 * @model
 * @generated
 */
public interface Ziel_Wunsch extends EObject
{
  /**
   * Returns the value of the '<em><b>Goal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Goal</em>' attribute.
   * @see #setGoal(String)
   * @see de.htwdd.sf.beleg.s85769s88750.myDsl.MyDslPackage#getZiel_Wunsch_Goal()
   * @model
   * @generated
   */
  String getGoal();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s85769s88750.myDsl.Ziel_Wunsch#getGoal <em>Goal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Goal</em>' attribute.
   * @see #getGoal()
   * @generated
   */
  void setGoal(String value);

  /**
   * Returns the value of the '<em><b>Infinitiv</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Infinitiv</em>' containment reference.
   * @see #setInfinitiv(Infinitiv)
   * @see de.htwdd.sf.beleg.s85769s88750.myDsl.MyDslPackage#getZiel_Wunsch_Infinitiv()
   * @model containment="true"
   * @generated
   */
  Infinitiv getInfinitiv();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s85769s88750.myDsl.Ziel_Wunsch#getInfinitiv <em>Infinitiv</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Infinitiv</em>' containment reference.
   * @see #getInfinitiv()
   * @generated
   */
  void setInfinitiv(Infinitiv value);

} // Ziel_Wunsch
