/*
 * generated by Xtext 2.30.0
 */
package de.htwdd.sf.beleg.s85769s88750.ui.labeling;

import com.google.inject.Inject;

import de.htwdd.sf.beleg.s85769s88750.myDsl.Nutzen;
import de.htwdd.sf.beleg.s85769s88750.myDsl.Rolle;
import de.htwdd.sf.beleg.s85769s88750.myDsl.Title;
import de.htwdd.sf.beleg.s85769s88750.myDsl.User_Story;
import de.htwdd.sf.beleg.s85769s88750.myDsl.Ziel_Wunsch;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class MyDslLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public MyDslLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	String text(User_Story ele) {
		return "User Story : " + ele.getTitle().getSubstantiv() + " " + ele.getTitle().getInfinitiv().getWord();
	}
 
	String text(Title ele) {
		return "Title : " + ele.getSubstantiv() + " " + ele.getInfinitiv().getWord();
	}
	String text(Rolle ele) {
		return "Rolle : " + ele.getSubstantiv();
	}
	String text(Nutzen ele) {
		return "Nutzen : " + ele.getSubject() + " "+ ele.getVerb();
	}
	String text(Ziel_Wunsch ele) {
		return "Ziel und Wunsch : " + ele.getGoal() + " "+ ele.getInfinitiv().getWord();
	}
	
}
