/*
 * generated by Xtext 2.30.0
 */
package de.htwdd.sf.beleg.s85769s88750.ui;

import com.google.inject.Injector;
import de.htwdd.sf.beleg.s85769s88750.ui.internal.S85769s88750Activator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(S85769s88750Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		S85769s88750Activator activator = S85769s88750Activator.getInstance();
		return activator != null ? activator.getInjector(S85769s88750Activator.DE_HTWDD_SF_BELEG_S85769S88750_MYDSL) : null;
	}

}
