/**
 * generated by Xtext 2.30.0
 */
package de.htwdd.sf.beleg.s85769s88750.myDsl.impl;

import de.htwdd.sf.beleg.s85769s88750.myDsl.Infinitiv;
import de.htwdd.sf.beleg.s85769s88750.myDsl.MyDslPackage;
import de.htwdd.sf.beleg.s85769s88750.myDsl.Ziel_Wunsch;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ziel Wunsch</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s85769s88750.myDsl.impl.Ziel_WunschImpl#getGoal <em>Goal</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s85769s88750.myDsl.impl.Ziel_WunschImpl#getInfinitiv <em>Infinitiv</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Ziel_WunschImpl extends MinimalEObjectImpl.Container implements Ziel_Wunsch
{
  /**
   * The default value of the '{@link #getGoal() <em>Goal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGoal()
   * @generated
   * @ordered
   */
  protected static final String GOAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getGoal() <em>Goal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGoal()
   * @generated
   * @ordered
   */
  protected String goal = GOAL_EDEFAULT;

  /**
   * The cached value of the '{@link #getInfinitiv() <em>Infinitiv</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInfinitiv()
   * @generated
   * @ordered
   */
  protected Infinitiv infinitiv;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Ziel_WunschImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.ZIEL_WUNSCH;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getGoal()
  {
    return goal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGoal(String newGoal)
  {
    String oldGoal = goal;
    goal = newGoal;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ZIEL_WUNSCH__GOAL, oldGoal, goal));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Infinitiv getInfinitiv()
  {
    return infinitiv;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInfinitiv(Infinitiv newInfinitiv, NotificationChain msgs)
  {
    Infinitiv oldInfinitiv = infinitiv;
    infinitiv = newInfinitiv;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ZIEL_WUNSCH__INFINITIV, oldInfinitiv, newInfinitiv);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInfinitiv(Infinitiv newInfinitiv)
  {
    if (newInfinitiv != infinitiv)
    {
      NotificationChain msgs = null;
      if (infinitiv != null)
        msgs = ((InternalEObject)infinitiv).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ZIEL_WUNSCH__INFINITIV, null, msgs);
      if (newInfinitiv != null)
        msgs = ((InternalEObject)newInfinitiv).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ZIEL_WUNSCH__INFINITIV, null, msgs);
      msgs = basicSetInfinitiv(newInfinitiv, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ZIEL_WUNSCH__INFINITIV, newInfinitiv, newInfinitiv));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.ZIEL_WUNSCH__INFINITIV:
        return basicSetInfinitiv(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.ZIEL_WUNSCH__GOAL:
        return getGoal();
      case MyDslPackage.ZIEL_WUNSCH__INFINITIV:
        return getInfinitiv();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.ZIEL_WUNSCH__GOAL:
        setGoal((String)newValue);
        return;
      case MyDslPackage.ZIEL_WUNSCH__INFINITIV:
        setInfinitiv((Infinitiv)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ZIEL_WUNSCH__GOAL:
        setGoal(GOAL_EDEFAULT);
        return;
      case MyDslPackage.ZIEL_WUNSCH__INFINITIV:
        setInfinitiv((Infinitiv)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ZIEL_WUNSCH__GOAL:
        return GOAL_EDEFAULT == null ? goal != null : !GOAL_EDEFAULT.equals(goal);
      case MyDslPackage.ZIEL_WUNSCH__INFINITIV:
        return infinitiv != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (goal: ");
    result.append(goal);
    result.append(')');
    return result.toString();
  }

} //Ziel_WunschImpl
