/*
 * generated by Xtext 2.30.0
 */
package de.htwdd.sf.beleg.s85769s88750.ui.tests;

import com.google.inject.Injector;
import de.htwdd.sf.beleg.s85769s88750.ui.internal.S85769s88750Activator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return S85769s88750Activator.getInstance().getInjector("de.htwdd.sf.beleg.s85769s88750.MyDsl");
	}

}
